package problem0389

/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

func findTheDifference(s string, t string) byte {
	var freq [26]int8
	// Calculate freq
	for i := range s {
		freq[s[i]-'a']++
		freq[t[i]-'a']--
	}
	freq[t[len(t)-1]-'a']--

	// Find missing
	for i := range freq {
		if freq[i] != 0 {
			return byte(i + 'a')
		}
	}
	return 0
}
